#!/usr/bin/env python3

# leo de config
# parseo

width = 5
height = 5

# 1. Declaración (reservar el espacio de 5x5)
maze = [[None] * width for _ in range(height)]

# 2. Asignación por posiciones [i][j]
for i in range(height):
    for j in range(width):
        maze[i][j] = '·'

print(maze)
print()

# 3. Impresión (el equivalente a tus printf de C)
for i in range(height):
    for j in range(width):
        print(maze[i][j], end=" ") # end=" " evita que haga un salto de línea tras cada carácter
    print() # Esto hace el salto de línea al terminar cada fila (tu maze = "\n")


'''
analogo de esto de c
char maze[width][height]; 

for (int i=0, i>5, i++)
    for (int j=0, j>5, j++)
        maze[i][j] = "·"
    maze = "\n"
'''